### PR TITLE
E2E: per-test store isolation with automatic teardown

### LINKED ISSUE #7269: E2E: Per-test store isolation for robust parallel execution
### Problem/Feature
When multiple tests share a dev store, earlier test failures can leave state (installed apps, modified config) that causes later tests to fail. Shared stores also prevent true parallel execution since `app dev` binds to a specific store.

### Proposed Solution
- **Per-test dev store creation:** `storeTestFixture` (test-scoped, not worker-scoped) creates a fresh dev store per test via browser automation on `admin.shopify.com/store-create/organization/{orgId}`
  - Handles shadow DOM form elements (`s-internal-text-field`, `s-internal-select`) using chained Playwright locators
  - Selects a random plan from available options
  - Waits for redirect to confirm store creation, extracts FQDN
- **Robust teardown with escalating retry** (`setup/teardown.ts`):
  - Phase 1: Uninstall app from store (verified via "Add apps to your store" empty state)
  - Phase 2: Delete store (verified via "Your plan was canceled" page). Escalates to phase 1 on failure (re-uninstall before retrying delete)
  - Phase 3: Delete app from dev dashboard (always runs, even if phases 1-2 fail)
  - Each phase is independent — failure never prevents later phases
- **Safety check:** `deleteStoreFromAdmin` refuses to delete if apps are still installed (prevents orphaned app installs)
- **Cleanup scripts** for manual/CI use:
  - `scripts/cleanup-stores.ts` — find and delete leftover E2E stores (uninstall apps first)
  - `scripts/cleanup-apps.ts` — find and delete leftover E2E apps from dev dashboard
  - `pnpm test:e2e-cleanup` runs both (stores first, then apps)
- **Tagged logging:** `[e2e][w0][browser]`, `[e2e][w1][cli]` etc. with section headers (`----- SETUP: store ... -----`, `----- TEARDOWN: app ... -----`) for debugging parallel output

**Expected result:** Each test is fully isolated — no shared store state, no cross-test interference, safe cleanup even on failure.

### LINKED ISSUE #7275: E2E: Improve error log
Current error log message is not super helpful. Need more meaningful log message.

### PR DESCRIPTION
**Pull request by phyllis-sy-wu**
Addressed https://github.com/Shopify/cli/issues/7269

### WHY are these changes introduced?

E2E tests currently share a single pre-existing dev store configured via `E2E_STORE_FQDN`. This causes:
- **Shared state**: earlier test failures can leave installed apps or modified config that affect later tests
- **No isolation**: tests can't run independently — one test's side effects leak into the next
- **Fragile teardown**: the old `teardownApp` silently skips steps, doesn't verify success, and a single failure blocks later cleanup

This PR also lays the foundation for parallel workers (future PR), where shared stores would be impossible since multiple tests run simultaneously.

### WHAT is this pull request doing?

**Per-test store isolation:**
- Tests that need a dev store (`app dev`, `hot reload`, `multi-config dev`, `toml-config dev`) create a fresh store via browser automation on `admin.shopify.com/store-create/organization/{orgId}`
- Each test gets its own isolated store — no shared state between tests
- Store is created in test setup and cleaned up in teardown

**Robust teardown with escalating retry** (`setup/teardown.ts`):

Three independent phases — failure in one never blocks the next:

- **Phase 1: Uninstall app from store** (3 attempts)
  - Navigates to store admin `/settings/apps`, finds app by name, clicks uninstall
  - Verifies app is gone (checks immediately, reloads once if still visible)
  - Dismisses Dev Console panel via `h2:has-text("Dev Console")` → `button[aria-label="hide"]`

- **Phase 2: Delete store** (3 attempts)
  - Navigates to `/settings/apps` to check state
  - Detects if store already deleted (`access_account` redirect)
  - Verifies no apps installed via `isStoreAppsEmpty` (reloads once if stale)
  - Navigates to `/settings/plan`, clicks delete, checkbox, confirm
  - Verifies deletion via `access_account` URL

- **Phase 3: Delete app from dashboard** (3 attempts, always runs)
  - Searches dev dashboard with pagination for app by name
  - Clicks delete on settings page, confirms via `button.critical[type="submit"]`
  - Handles 500/502 errors: `refreshIfPageError` detects error pages and refreshes
  - Detects 404 after refresh as confirmation of successful deletion

**Server error handling** (`setup/browser.ts`):
- `refreshIfPageError(page)` detects 500/502 error pages and auto-refreshes
- Used across dashboard navigation, pagination, and app deletion retry loops

**Tagged logging** (`setup/env.ts`):
- `createLogger(tag)` produces `[e2e][w0][browser]`, `[e2e][w0][cli]` format
- `e2eSection()` prints section headers: `----- SETUP: store ... -----`, `----- TEARDOWN: app ... -----`
- Clear per-attempt failure messages with specific reasons

**Exported building blocks** (`setup/store.ts`):
- `uninstallAppFromStore(page, storeSlug, appName)` → boolean
- `deleteStore(page, storeSlug)` → boolean
- `isStoreAppsEmpty(page)` → boolean (pure page checker, caller navigates)
- `dismissDevConsole(page)` → void

**Files changed:**

| File | Change |
|------|--------|
| `setup/store.ts` | New: store creation, deletion, uninstall, fixtures, helpers |
| `setup/teardown.ts` | New: `teardownAll()` orchestrator with 3-phase teardown |
| `setup/app.ts` | Extract `findAppOnDevDashboard()` (with pagination), `deleteAppFromDevDashboard()` |
| `setup/env.ts` | Add `createLogger()`, `e2eSection()`, `workerIndex` |
| `setup/cli.ts` | Worker-tagged logging for exec/spawn |
| `setup/browser.ts` | Add `refreshIfPageError()` |
| All test files | Switch to `teardownAll`, store-dependent tests use `storeTestFixture` |

### How to test your changes?

```bash
# Run all tests with debug output
DEBUG=1 pnpm --filter e2e exec playwright test

# Run headed to watch store creation/teardown
E2E_HEADED=1 DEBUG=1 pnpm --filter e2e exec playwright test

# Skip teardown for debugging (clean up manually after)
E2E_SKIP_CLEANUP=1 pnpm --filter e2e exec playwright test
```

### Checklist

- [x] I've considered possible cross-platform impacts (Mac, Linux, Windows)
- [ ] I've considered possible [documentation](https://shopify.dev) changes
- [ ] I've considered analytics changes to measure impact
- [ ] The change is user-facing, so I've added a changelog entry with `pnpm changeset add`

### CODE REVIEW

**Comment by phyllis-sy-wu** [comment]
* **#7309** <a href="https://app.graphite.com/github/pr/Shopify/cli/7309?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 3  dependent PRs ([#7343](https://github.com/Shopify/cli/pull/7343) <a href="https://app.graphite.com/github/pr/Shopify/cli/7343?utm_source=stack-comment-icon" target="_blank">Graphite</a>, [#7349](https://github.com/Shopify/cli/pull/7349) <a href="https://app.graphite.com/github/pr/Shopify/cli/7349?utm_source=stack-comment-icon" target="_blank">Graphite</a>, [#7350](https://github.com/Shopify/cli/pull/7350) <a href="https://app.graphite.com/github/pr/Shopify/cli/7350?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#7279** <a href="https://app.graphite.com/github/pr/Shopify/cli/7279?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/Shopify/cli/7279?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#7282** <a href="https://app.graphite.com/github/pr/Shopify/cli/7282?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#7281** <a href="https://app.graphite.com/github/pr/Shopify/cli/7281?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#7272** <a href="https://app.graphite.com/github/pr/Shopify/cli/7272?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: packages/e2e/setup/teardown.ts [hunk 1]
```diff
@@ -0,0 +1,146 @@
...
+export async function teardownAll(ctx: TeardownCtx): Promise<void> {
+  const wCtx = {workerIndex: ctx.workerIndex ?? 0}
+  const page = ctx.browserPage
+
+  // Phase 1 + 2: Store cleanup (app+store tests only)
+  if (ctx.storeFqdn) {
+    const storeSlug = ctx.storeFqdn.replace('.myshopify.com', '')
+    e2eSection(wCtx, `Teardown: store ${ctx.storeFqdn}`)
+
+    // Phase 1: Uninstall app from store
```
Comment (gonzaloriestra) [inline packages/e2e/setup/teardown.ts:43]: If we are deleting the store in the next step, why uninstalling the app?

File: packages/e2e/setup/store.ts [hunk 2]
```diff
@@ -0,0 +1,301 @@
...
+): Promise<string> {
+  const {browserPage} = ctx
+  const orgId = ctx.orgId ?? (process.env.E2E_ORG_ID ?? '').trim()
+
+  e2eSection(ctx, `Setup: store ${ctx.storeName}`)
+  log.log(ctx, 'store creating')
+
+  // Navigate directly to the store creation form on admin.shopify.com
+  const email = ctx.email ?? process.env.E2E_ACCOUNT_EMAIL
+  await browserPage.goto(`https://admin.shopify.com/store-create/organization/${orgId}`, {
```
Comment (gonzaloriestra) [inline packages/e2e/setup/store.ts:44]: We will need to switch soon to a CLI command: https://github.com/Shopify/cli/pull/7332

**Review by gonzaloriestra — APPROVED** [review]

File: packages/e2e/setup/teardown.ts (hunk 1 above)
Comment (phyllis-sy-wu) [reply packages/e2e/setup/teardown.ts:43]: Because deleting a store won't automatically uninstall the apps that were installed on it. Right now, if we delete a store with apps installed, the install count will go stale on dev dashboard, and those apps will not be able to be deleted after the store is deleted! It's a bug I discovered recently, documented [here with more details](https://shopify.slack.com/archives/C01D7U7AJ5C/p1775845842850389).
